name: Manually Triggered by Input
on:
  workflow_dispatch: 
    inputs:
      string:
        description: A String Input
        type: string
        required: true
        default: "Default Value"
      number: 
        description: A Number Input
        default: 4
        type: number


jobs:
  log-info: 
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_REF
      # Access out input defined above.
      - run: |
          echo "String: ${{ inputs.string }}"
          echo "Number: ${{ inputs.number }}"
  
# We are print from inputs > string.