name: Working Dir and shells
on: [push]

jobs: 
  display-directory-and-list-files:
    runs-on: ubuntu-latest
    steps:
      - name: Display working directory and list files
        run: | 
          pwd
          ls -l
          echo $GITHUB_WORKSPACE

      - name: Change Directory to /home/runner
        working-directory: /home/runner
        run: pwd
        
  display-dir-and-list-files-on-windiow:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh # use powershell for windows.
    steps:  
      - name: Displah Dir and List files on windows
        run: | 
          Get-Location
          dir
          echo $env:GITHUB_WORKSPACE